### PR TITLE
Fix #58: Avoid shifting UI on alert

### LINKED ISSUE #58: UI: "Connected to only one peer" banner keeps on shifting the UI
Originally in https://github.com/paritytech/parity/issues/8422 by @chevdor

> I'm running:
>
> - **Which Parity version?**: Parity/v1.11.0-unstable-0a170efaa-20180411/x86_64-macos/rustc1.25.0
> - **Which operating system?**: Windows / **MacOS** / Linux
> - **How installed?**: via installer / homebrew / binaries / **from source**
> - **Are you fully synchronized?**: no / **yes**
> - **Which network are you connected to?**: ethereum / ropsten / **kovan** / ...
> - **Did you try to restart the node?**: no / **yes**

For whatever reason, my node is now alternating between having 1 and 2 peers. This is not great but that´s what it is now.

The way the UI is built makes very annoying as the red banner saying "You are connected to only one peer. Your node might not be reliable. Check your network connection." is shifting the UI down and up and down and up. This makes parity totally unusable as you will likely click on the wrong UI element.

A simple workaround would be to show the banner as overlay and stop shifting the UI down.

### PR DESCRIPTION
**Pull request by chevdor**
See #58 and https://github.com/paritytech/parity/issues/8422

While I don't find the solution amazing (this is more a workaround), it does fix the issue and makes the UI usable again. Please let me know if you see other options.

Is there by the way a UI guideline somewhere? I think the notification system in general would benefit some rework and I am sure you already have plan/ideas.

### CODE REVIEW

**Comment by amaurymartiny** [comment]
@chevdor, thanks for the PR!

I believe this PR needs some small changes. If I go in my Parity Wallet, the overlay hides most of the top bar. If there are 2 such messages, then Parity Wallet becomes unusable.

screen shot 2018-04-19 at 4 06 53 pm

A possible idea would be a close button + timer like suggested in #58. The close button would trigger not showing any banners for the next x seconds.

About the red/orange color, there are some messages (such as `'You are not connected to any peers. There is most likely some network issue. Fix connectivity.'`) which are definitely errors. However I'm not opiniated about red or orange, so I'm ok with your choice.

**Comment by jacogr** [comment]
I think the quickest hack is probably along the lines of what @chevdor did, but move it to the bottom if the overlay is an issue. UI usable, banner still in your face. Thoughts @amaurymartiny  ?

**Comment by chevdor** [comment]
I though about using the bottom and we can try but this is an area where
there are already notifications such as the tx confirmation input dialog,
the tx confirmation dialog.

I also experimented a bit with some max-height what I ended up not
commiting as it was far from great with some of the messages.

My suggestion would be to tweak this PR with sizes that work for most and
then think about the UI as a whole in another PR:
- what are errors
- what are warnings
- where do notifications show up etc...

**Comment by chevdor** [comment]
@amaurymartiny can you point to the alternate solution?

**Comment by amaurymartiny** [comment]
@chevdor I'd still go with an overlay (so that UI doesn't shift), with a x button + a timer. https://github.com/parity-js/shell/issues/58#issuecomment-382304711

**Pull request closed without merging**
